import { Teacher, Discipline, Student } from '../types';

// DADOS ESTÁTICOS PARA MODO OFFLINE/FALLBACK
// Extraídos de restaurar_dados.sql

export const STATIC_TEACHERS: Teacher[] = [
    { id: 'assuncao', name: 'Assunção', avatar: 'https://ui-avatars.com/api/?name=Assuncao&background=random' },
    { id: 'carmem', name: 'Carmem', avatar: 'https://ui-avatars.com/api/?name=Carmem&background=random' },
    { id: 'daniel', name: 'Daniel', avatar: 'https://ui-avatars.com/api/?name=Daniel&background=random' },
    { id: 'denilson', name: 'Denilson', avatar: 'https://ui-avatars.com/api/?name=Denilson&background=random' },
    { id: 'ednardo', name: 'Ednardo', avatar: 'https://ui-avatars.com/api/?name=Ednardo&background=random' },
    { id: 'eunice', name: 'Eunice', avatar: 'https://ui-avatars.com/api/?name=Eunice&background=random' },
    { id: 'francineuda', name: 'Francineuda', avatar: 'https://ui-avatars.com/api/?name=Francineuda&background=random' },
    { id: 'francisca', name: 'Francisca', avatar: 'https://ui-avatars.com/api/?name=Francisca&background=random' },
    { id: 'helane', name: 'Helane', avatar: 'https://ui-avatars.com/api/?name=Helane&background=random' },
    { id: 'jandira', name: 'Jandira', avatar: 'https://ui-avatars.com/api/?name=Jandira&background=random' },
    { id: 'joanilson', name: 'Joanilson', avatar: 'https://ui-avatars.com/api/?name=Joanilson&background=random' },
    { id: 'jorge', name: 'Jorge', avatar: 'https://ui-avatars.com/api/?name=Jorge&background=random' },
    { id: 'lindelvania', name: 'Lindelvania', avatar: 'https://ui-avatars.com/api/?name=Lindelvania&background=random' },
    { id: 'luciano', name: 'Luciano', avatar: 'https://ui-avatars.com/api/?name=Luciano&background=random' },
    { id: 'marcos', name: 'Marcos', avatar: 'https://ui-avatars.com/api/?name=Marcos&background=random' },
    { id: 'mizael', name: 'Mizael', avatar: 'https://ui-avatars.com/api/?name=Mizael&background=random' },
    { id: 'paulo', name: 'Paulo', avatar: 'https://ui-avatars.com/api/?name=Paulo&background=random' },
    { id: 'wesley', name: 'Wesley', avatar: 'https://ui-avatars.com/api/?name=Wesley&background=random' },
    { id: 'wilsilene', name: 'Wilsilene (Leninha)', avatar: 'https://ui-avatars.com/api/?name=Wilsilene&background=random' },
    { id: 'wilson', name: 'Wilson', avatar: 'https://ui-avatars.com/api/?name=Wilson&background=random' }
];

export const STATIC_DISCIPLINES: Discipline[] = [
    { id: 'assuncao-geo', name: 'Geografia', teacherId: 'assuncao', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D', 'VII ETAPA'], totalHours: 0 },
    { id: 'carmem-ing', name: 'Inglês', teacherId: 'carmem', classes: ['MÓDULO II-A', 'MÓDULO II-B'], totalHours: 0 },
    { id: 'daniel-soc', name: 'Sociologia', teacherId: 'daniel', classes: ['MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'denilson-so', name: 'Sistemas Operacionais', teacherId: 'denilson', classes: ['MÓDULO II-A', 'MÓDULO II-B'], totalHours: 0 },
    { id: 'denilson-arq', name: 'Arquitetura e Manutenção', teacherId: 'denilson', classes: ['MÓDULO II-A', 'MÓDULO II-B'], totalHours: 0 },
    { id: 'ednardo-fis', name: 'Física', teacherId: 'ednardo', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'ednardo-eletiva', name: 'Eletiva Orientada', teacherId: 'ednardo', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'eunice-port', name: 'Língua Portuguesa', teacherId: 'eunice', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'francineuda-port', name: 'Língua Portuguesa', teacherId: 'francineuda', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'francisca-hist', name: 'História', teacherId: 'francisca', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D', 'VII ETAPA'], totalHours: 0 },
    { id: 'helane-bio', name: 'Biologia', teacherId: 'helane', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'jandira-edfis', name: 'Educação Física', teacherId: 'jandira', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'VII ETAPA'], totalHours: 0 },
    { id: 'joanilson-arte', name: 'Arte', teacherId: 'joanilson', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'joanilson-fil', name: 'Filosofia', teacherId: 'joanilson', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'joanilson-pv', name: 'Projeto de Vida', teacherId: 'joanilson', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'joanilson-soc', name: 'Sociologia', teacherId: 'joanilson', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'jorge-fis', name: 'Física', teacherId: 'jorge', classes: ['MÓDULO II-A', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'lindelvania-esp', name: 'Espanhol', teacherId: 'lindelvania', classes: ['MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'lindelvania-ing', name: 'Inglês', teacherId: 'lindelvania', classes: ['VII ETAPA'], totalHours: 0 },
    { id: 'luciano-progweb', name: 'Programação para Web', teacherId: 'luciano', classes: ['MÓDULO IV-A', 'MÓDULO IV-B'], totalHours: 0 },
    { id: 'luciano-redes', name: 'Redes de Computadores', teacherId: 'luciano', classes: ['MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'marcos-progweb', name: 'Programação para Web', teacherId: 'marcos', classes: ['MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'marcos-pai', name: 'Proj. Aprendizagem Interdisciplinar', teacherId: 'marcos', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'mizael-bd', name: 'Banco de Dados', teacherId: 'mizael', classes: ['MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'mizael-ed', name: 'Estrutura de Dados', teacherId: 'mizael', classes: ['MÓDULO II-A', 'MÓDULO II-B'], totalHours: 0 },
    { id: 'paulo-arte', name: 'Arte', teacherId: 'paulo', classes: ['MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D'], totalHours: 0 },
    { id: 'wesley-mat', name: 'Matemática', teacherId: 'wesley', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D', 'VII ETAPA'], totalHours: 0 },
    { id: 'wilsilene-quim', name: 'Química', teacherId: 'wilsilene', classes: ['MÓDULO II-A', 'MÓDULO II-B', 'MÓDULO IV-A', 'MÓDULO IV-B', 'MÓDULO IV-C', 'MÓDULO IV-D', 'VII ETAPA'], totalHours: 0 },
    { id: 'wilson-bio', name: 'Biologia', teacherId: 'wilson', classes: ['VII ETAPA'], totalHours: 0 }
];

export const STATIC_STUDENTS: Student[] = [
    // MÓDULO II-A
    { id: 'mod2a-1', name: 'AMADEU DAVID CORTEZ NUNES', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-2', name: 'ANA CAROLINA RODRIGUES DE SOUZA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-3', name: 'BRENDA KALYNE FERREIRA DE OLIVEIRA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-4', name: 'FELIPE DE OLIVEIRA ARAUJO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-5', name: 'FLÁVIO WILLIAM SILVA SOUSA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-6', name: 'GUILHERME RODRIGUES DA SILVA GONCALVES', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-7', name: 'HENRY LUIS GOMES QUEIROZ SANTANA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-8', name: 'ISAMARA JOVITA ARAUJO TORRES', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-9', name: 'JACKSON DA COSTA SANTOS', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-10', name: 'JANA CLEA FERREIRA DE CARVALHO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-11', name: 'JOSE GONCALVES DE ARAUJO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-12', name: 'LARISSA ANTONELA DA SILVA PACIFICO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-13', name: 'LUIS CARLOS CRUZ SILVA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-14', name: 'MARCOS SILVA DE OLIVEIRA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-15', name: 'MARIA ANTONIA VIEIRA DA SILVA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-16', name: 'MARIA ELIANE DE SOUSA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-17', name: 'MARIA VITÓRIA FREITAS GALVÃO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-18', name: 'SABRINA LIMA OLIVEIRA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-19', name: 'SAYANE VITORIA DOS SANTOS SOUSA LIMA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-20', name: 'SUZANA RAQUEL SANTOS SILVA', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },
    { id: 'mod2a-21', name: 'THIAGO DANIEL DA SILVA PINTO', class: 'MÓDULO II-A', photoUrl: '', status: 'present' },

    // MÓDULO II-B
    { id: 'mod2b-1', name: 'ADRIANA CONCEIÇÃO PEREIRA DE ALMEIDA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-2', name: 'ALINE GONCALVES DE MELO', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-3', name: 'DADIANE MARIA DA SILVA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-4', name: 'ERLANE NASCIMENTO DE SOUSA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-5', name: 'FRANCIMAURA DE SOUSA VELÔSO', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-6', name: 'FRANCISCA MARIA DOS SANTOS BRAGA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-7', name: 'GUILHERME DOS SANTOS BRITO', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-8', name: 'IASMIN ROCHA DOS SANTOS', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-9', name: 'ISADORA AGUIAR DOS SANTOS', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-10', name: 'JAQUELINE', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-11', name: 'JOSÉ BALDOMIRO BEZERRA DE SOUSA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-12', name: 'LINDALVA PEREIRA DOS SANTOS', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-13', name: 'LUCAS SAMUEL DE SOUSA SILVA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-14', name: 'MARIA DA GLORIA FERREIRA DÓRIA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-15', name: 'MARIA RAMOS DO NASCIMENTO', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-16', name: 'MARLENE DE OLIVEIRA MORAES', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-17', name: 'PEDRO HENRIQUE ALVES DA SILVA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-18', name: 'RAILTON GABRIEL PEREIRA DOS SANTOS', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-19', name: 'TAMIRES SOUSA DOS SANTOS', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },
    { id: 'mod2b-20', name: 'VANESSA ADRIELE SOARES DA SILVA', class: 'MÓDULO II-B', photoUrl: '', status: 'present' },

    // MÓDULO IV-A
    { id: 'mod4a-1', name: 'BELINA OLIVAL LIMA FAUSTINO', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-2', name: 'CIBELE BRITO DO NASCIMENTO ANDRADE', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-3', name: 'DANIELE VITORIA CARNEIRO GOMES', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-4', name: 'FABIÚLA MEDEIROS ASSUNÇÃO', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-5', name: 'GIOVANNA DE MOURA FREITAS SILVA LIMA', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-6', name: 'IAGO ASSUNÇÃO SIMIÃO DA SILVA', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-7', name: 'ISRAEL DE OLIVEIRA SANTOS', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-8', name: 'JOSÉ HOLANDA MENDES', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-9', name: 'KAIRO WESLEY ALVES FRASAO', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-10', name: 'LUCAS VINICIO PINTO FONTINELE', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-11', name: 'LUCIA JULIANA DE ARAÚJO', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-12', name: 'PAULA LAIZE DOS SANTOS OLIVEIRA', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-13', name: 'PRISCILA AROUCHA DOS SANTOS', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },
    { id: 'mod4a-14', name: 'RAYCILLA ANNYELLE SOUSA DE ARAUJO', class: 'MÓDULO IV-A', photoUrl: '', status: 'present' },

    // VII ETAPA
    { id: 'vii-1', name: 'ALISSON CLEBERT PINTO PEREIRA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-2', name: 'ANA TERESA DA SILVA SOUSA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-3', name: 'ANNA GABRYELLA TORRES COSTA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-4', name: 'ANTONIEL SANTOS DE OLIVEIRA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-5', name: 'BRUNO GUIDO DA SILVA LEAL', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-6', name: 'CAMILIA MARIA DE SOUSA COSTA ALVES', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-7', name: 'CARLOS HENRIQUE SANTOS FARIAS', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-8', name: 'CHRISTYAN KAUAN SANTOS DA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-9', name: 'CLARA KELLY SILVA BEZERRA LOPES', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-10', name: 'DANIELA VIEIRA DA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-11', name: 'ESDRAS SHINAYDER LEITE SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-12', name: 'ESHILEY VITORIA DE AGUIAR BORGES', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-13', name: 'FRANCIELLY DE SOUSA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-14', name: 'GEORGE LUIZ MOURA DOS SANTOS', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-15', name: 'HELLEN LETICIA LIMA E SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-16', name: 'ISLAINE VITÓRIA VIANA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-17', name: 'JUAN KELLME CORTEZ SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-18', name: 'LUCIANA DE SANTANA LIMA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-19', name: 'MARIA DO SOCORRO NEVES DA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-20', name: 'MARLY DE OLIVEIRA MORAES', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-21', name: 'MATEUS DA SILVA ARAUJO', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-22', name: 'MATEUS GOMES DOURADO', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-23', name: 'NAYSLA BEATRIZ DE SOUSA FERREIRA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-24', name: 'PABLO HENRIQUE PORTELA RODRIGUES DA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-25', name: 'SUYANE MARIA SILVA SANTOS OLIVEIRA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-26', name: 'THALLYSON DAVI DA SILVA LIMA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-27', name: 'VICTOR WAGNER SOUSA BARBOSA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-28', name: 'VITORIA MAURIELI DOS SANTOS DA SILVA', class: 'VII ETAPA', photoUrl: '', status: 'present' },
    { id: 'vii-29', name: 'YANA CAROLINE VIEIRA DE SOUSA', class: 'VII ETAPA', photoUrl: '', status: 'present' }
];
